/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetAnnotationRequest
 */
export interface AssetAnnotationRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AssetAnnotationRequest
     */
    annotations?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AssetAnnotationRequest interface.
 */
export function instanceOfAssetAnnotationRequest(value: object): boolean {
    return true;
}

export function AssetAnnotationRequestFromJSON(json: any): AssetAnnotationRequest {
    return AssetAnnotationRequestFromJSONTyped(json, false);
}

export function AssetAnnotationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetAnnotationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
    };
}

export function AssetAnnotationRequestToJSON(value?: AssetAnnotationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'annotations': value['annotations'],
    };
}

