/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetPayload
 */
export interface AssetPayload {
    /**
     * The alias of the asset in Vulcan
     * @type {string}
     * @memberof AssetPayload
     */
    alias?: string;
    /**
     * Environmental CVSS
     * @type {string}
     * @memberof AssetPayload
     */
    environmentalCvss?: string;
    /**
     * Identifier
     * @type {string}
     * @memberof AssetPayload
     */
    identifier: string;
    /**
     * Options
     * @type {string}
     * @memberof AssetPayload
     */
    options?: string;
    /**
     * Rolfp plus scope vector
     * @type {string}
     * @memberof AssetPayload
     */
    rolfp?: string;
    /**
     * Scannable
     * @type {boolean}
     * @memberof AssetPayload
     */
    scannable?: boolean;
    /**
     * Type
     * @type {string}
     * @memberof AssetPayload
     */
    type?: string;
}

/**
 * Check if a given object implements the AssetPayload interface.
 */
export function instanceOfAssetPayload(value: object): boolean {
    if (!('identifier' in value)) return false;
    return true;
}

export function AssetPayloadFromJSON(json: any): AssetPayload {
    return AssetPayloadFromJSONTyped(json, false);
}

export function AssetPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'environmentalCvss': json['environmental_cvss'] == null ? undefined : json['environmental_cvss'],
        'identifier': json['identifier'],
        'options': json['options'] == null ? undefined : json['options'],
        'rolfp': json['rolfp'] == null ? undefined : json['rolfp'],
        'scannable': json['scannable'] == null ? undefined : json['scannable'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AssetPayloadToJSON(value?: AssetPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'alias': value['alias'],
        'environmental_cvss': value['environmentalCvss'],
        'identifier': value['identifier'],
        'options': value['options'],
        'rolfp': value['rolfp'],
        'scannable': value['scannable'],
        'type': value['type'],
    };
}

