/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetGroupPayload
 */
export interface AssetGroupPayload {
    /**
     * Asset ID
     * @type {string}
     * @memberof AssetGroupPayload
     */
    assetId: string;
}

export function AssetGroupPayloadFromJSON(json: any): AssetGroupPayload {
    return AssetGroupPayloadFromJSONTyped(json, false);
}

export function AssetGroupPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetGroupPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetId': json['asset_id'],
    };
}

export function AssetGroupPayloadToJSON(value?: AssetGroupPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset_id': value.assetId,
    };
}


