/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetPayload
 */
export interface AssetPayload {
    /**
     * The alias of the asset in Vulcan
     * @type {string}
     * @memberof AssetPayload
     */
    alias?: string;
    /**
     * Environmental CVSS
     * @type {string}
     * @memberof AssetPayload
     */
    environmentalCvss?: string;
    /**
     * Identifier
     * @type {string}
     * @memberof AssetPayload
     */
    identifier: string;
    /**
     * Options
     * @type {string}
     * @memberof AssetPayload
     */
    options?: string;
    /**
     * Rolfp plus scope vector
     * @type {string}
     * @memberof AssetPayload
     */
    rolfp?: string;
    /**
     * Scannable
     * @type {boolean}
     * @memberof AssetPayload
     */
    scannable?: boolean;
    /**
     * Type
     * @type {string}
     * @memberof AssetPayload
     */
    type?: string;
}

export function AssetPayloadFromJSON(json: any): AssetPayload {
    return AssetPayloadFromJSONTyped(json, false);
}

export function AssetPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'environmentalCvss': !exists(json, 'environmental_cvss') ? undefined : json['environmental_cvss'],
        'identifier': json['identifier'],
        'options': !exists(json, 'options') ? undefined : json['options'],
        'rolfp': !exists(json, 'rolfp') ? undefined : json['rolfp'],
        'scannable': !exists(json, 'scannable') ? undefined : json['scannable'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function AssetPayloadToJSON(value?: AssetPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'environmental_cvss': value.environmentalCvss,
        'identifier': value.identifier,
        'options': value.options,
        'rolfp': value.rolfp,
        'scannable': value.scannable,
        'type': value.type,
    };
}


