/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetWithAnnotationsPayload
 */
export interface AssetWithAnnotationsPayload {
    /**
     * The alias of the asset in Vulcan
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    alias?: string;
    /**
     * The provided annotations may differ from the ones that
     * will be stored, because they will include a prefix to not mess with any other
     * annotations already present in the asset.
     * @type {{ [key: string]: any; }}
     * @memberof AssetWithAnnotationsPayload
     */
    annotations?: { [key: string]: any; };
    /**
     * Environmental CVSS
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    environmentalCvss?: string;
    /**
     * Identifier
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    identifier: string;
    /**
     * Options
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    options?: string;
    /**
     * Rolfp plus scope vector
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    rolfp?: string;
    /**
     * Scannable
     * @type {boolean}
     * @memberof AssetWithAnnotationsPayload
     */
    scannable?: boolean;
    /**
     * Type
     * @type {string}
     * @memberof AssetWithAnnotationsPayload
     */
    type: string;
}

/**
 * Check if a given object implements the AssetWithAnnotationsPayload interface.
 */
export function instanceOfAssetWithAnnotationsPayload(value: object): boolean {
    if (!('identifier' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function AssetWithAnnotationsPayloadFromJSON(json: any): AssetWithAnnotationsPayload {
    return AssetWithAnnotationsPayloadFromJSONTyped(json, false);
}

export function AssetWithAnnotationsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetWithAnnotationsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
        'environmentalCvss': json['environmental_cvss'] == null ? undefined : json['environmental_cvss'],
        'identifier': json['identifier'],
        'options': json['options'] == null ? undefined : json['options'],
        'rolfp': json['rolfp'] == null ? undefined : json['rolfp'],
        'scannable': json['scannable'] == null ? undefined : json['scannable'],
        'type': json['type'],
    };
}

export function AssetWithAnnotationsPayloadToJSON(value?: AssetWithAnnotationsPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'alias': value['alias'],
        'annotations': value['annotations'],
        'environmental_cvss': value['environmentalCvss'],
        'identifier': value['identifier'],
        'options': value['options'],
        'rolfp': value['rolfp'],
        'scannable': value['scannable'],
        'type': value['type'],
    };
}

