/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Assettype } from './Assettype';
import {
    AssettypeFromJSON,
    AssettypeFromJSONTyped,
    AssettypeToJSON,
} from './Assettype';

/**
 * Asset (default view)
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * Alias
     * @type {string}
     * @memberof Asset
     */
    alias?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Asset
     */
    annotations?: { [key: string]: any; };
    /**
     * Classified At
     * @type {string}
     * @memberof Asset
     */
    classifiedAt?: string;
    /**
     * Environmental CVSS
     * @type {string}
     * @memberof Asset
     */
    environmentalCvss?: string;
    /**
     * Asset ID
     * @type {string}
     * @memberof Asset
     */
    id?: string;
    /**
     * Identifier
     * @type {string}
     * @memberof Asset
     */
    identifier?: string;
    /**
     * Options
     * @type {string}
     * @memberof Asset
     */
    options?: string;
    /**
     * Rolfp plus scope vector
     * @type {string}
     * @memberof Asset
     */
    rolfp?: string;
    /**
     * Scannable
     * @type {boolean}
     * @memberof Asset
     */
    scannable?: boolean;
    /**
     * 
     * @type {Assettype}
     * @memberof Asset
     */
    type?: Assettype;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): boolean {
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
        'classifiedAt': json['classified_at'] == null ? undefined : json['classified_at'],
        'environmentalCvss': json['environmental_cvss'] == null ? undefined : json['environmental_cvss'],
        'id': json['id'] == null ? undefined : json['id'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'options': json['options'] == null ? undefined : json['options'],
        'rolfp': json['rolfp'] == null ? undefined : json['rolfp'],
        'scannable': json['scannable'] == null ? undefined : json['scannable'],
        'type': json['type'] == null ? undefined : AssettypeFromJSON(json['type']),
    };
}

export function AssetToJSON(value?: Asset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'alias': value['alias'],
        'annotations': value['annotations'],
        'classified_at': value['classifiedAt'],
        'environmental_cvss': value['environmentalCvss'],
        'id': value['id'],
        'identifier': value['identifier'],
        'options': value['options'],
        'rolfp': value['rolfp'],
        'scannable': value['scannable'],
        'type': AssettypeToJSON(value['type']),
    };
}

