/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Asset Type (default view)
 * @export
 * @interface Assettype
 */
export interface Assettype {
    /**
     * Asset Type ID
     * @type {string}
     * @memberof Assettype
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Assettype
     */
    name?: string;
}

/**
 * Check if a given object implements the Assettype interface.
 */
export function instanceOfAssettype(value: object): boolean {
    return true;
}

export function AssettypeFromJSON(json: any): Assettype {
    return AssettypeFromJSONTyped(json, false);
}

export function AssettypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assettype {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AssettypeToJSON(value?: Assettype | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

