/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Asset Annotations (default view)
 * @export
 * @interface AssetannotationsResponse
 */
export interface AssetannotationsResponse {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AssetannotationsResponse
     */
    annotations?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AssetannotationsResponse interface.
 */
export function instanceOfAssetannotationsResponse(value: object): boolean {
    return true;
}

export function AssetannotationsResponseFromJSON(json: any): AssetannotationsResponse {
    return AssetannotationsResponseFromJSONTyped(json, false);
}

export function AssetannotationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetannotationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
    };
}

export function AssetannotationsResponseToJSON(value?: AssetannotationsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'annotations': value['annotations'],
    };
}

