/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Asset Type (default view)
 * @export
 * @interface Assettype
 */
export interface Assettype {
    /**
     * Asset Type ID
     * @type {string}
     * @memberof Assettype
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Assettype
     */
    name?: string;
}

export function AssettypeFromJSON(json: any): Assettype {
    return AssettypeFromJSONTyped(json, false);
}

export function AssettypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assettype {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AssettypeToJSON(value?: Assettype | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

