/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * attachment (default view)
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * Content Type of the attachment
     * @type {string}
     * @memberof Attachment
     */
    contentType?: string;
    /**
     * attachment data
     * @type {object}
     * @memberof Attachment
     */
    data?: object;
    /**
     * Attachment name
     * @type {string}
     * @memberof Attachment
     */
    name?: string;
}

/**
 * Check if a given object implements the Attachment interface.
 */
export function instanceOfAttachment(value: object): boolean {
    return true;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'data': json['data'] == null ? undefined : json['data'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AttachmentToJSON(value?: Attachment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content_type': value['contentType'],
        'data': value['data'],
        'name': value['name'],
    };
}

