/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * attachment (default view)
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * Content Type of the attachment
     * @type {string}
     * @memberof Attachment
     */
    contentType?: string;
    /**
     * attachment data
     * @type {object}
     * @memberof Attachment
     */
    data?: object;
    /**
     * Attachment name
     * @type {string}
     * @memberof Attachment
     */
    name?: string;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentType': !exists(json, 'content_type') ? undefined : json['content_type'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AttachmentToJSON(value?: Attachment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content_type': value.contentType,
        'data': value.data,
        'name': value.name,
    };
}


