/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Statsaverages } from './Statsaverages';
import {
    StatsaveragesFromJSON,
    StatsaveragesFromJSONTyped,
    StatsaveragesToJSON,
} from './Statsaverages';

/**
 * Current exposure stats (default view)
 * @export
 * @interface CurrentExposure
 */
export interface CurrentExposure {
    /**
     * 
     * @type {Statsaverages}
     * @memberof CurrentExposure
     */
    currentExposure?: Statsaverages;
}

/**
 * Check if a given object implements the CurrentExposure interface.
 */
export function instanceOfCurrentExposure(value: object): boolean {
    return true;
}

export function CurrentExposureFromJSON(json: any): CurrentExposure {
    return CurrentExposureFromJSONTyped(json, false);
}

export function CurrentExposureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentExposure {
    if (json == null) {
        return json;
    }
    return {
        
        'currentExposure': json['current_exposure'] == null ? undefined : StatsaveragesFromJSON(json['current_exposure']),
    };
}

export function CurrentExposureToJSON(value?: CurrentExposure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'current_exposure': StatsaveragesToJSON(value['currentExposure']),
    };
}

