/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Statsaverages,
    StatsaveragesFromJSON,
    StatsaveragesFromJSONTyped,
    StatsaveragesToJSON,
} from './Statsaverages';

/**
 * Current exposure stats (default view)
 * @export
 * @interface CurrentExposure
 */
export interface CurrentExposure {
    /**
     * 
     * @type {Statsaverages}
     * @memberof CurrentExposure
     */
    currentExposure?: Statsaverages;
}

export function CurrentExposureFromJSON(json: any): CurrentExposure {
    return CurrentExposureFromJSONTyped(json, false);
}

export function CurrentExposureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentExposure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentExposure': !exists(json, 'current_exposure') ? undefined : StatsaveragesFromJSON(json['current_exposure']),
    };
}

export function CurrentExposureToJSON(value?: CurrentExposure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_exposure': StatsaveragesToJSON(value.currentExposure),
    };
}

