/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetWithAnnotationsPayload } from './AssetWithAnnotationsPayload';
import {
    AssetWithAnnotationsPayloadFromJSON,
    AssetWithAnnotationsPayloadFromJSONTyped,
    AssetWithAnnotationsPayloadToJSON,
} from './AssetWithAnnotationsPayload';

/**
 * 
 * @export
 * @interface DiscoveredAssetsPayload
 */
export interface DiscoveredAssetsPayload {
    /**
     * 
     * @type {Array<AssetWithAnnotationsPayload>}
     * @memberof DiscoveredAssetsPayload
     */
    assets?: Array<AssetWithAnnotationsPayload>;
    /**
     * The discovery group name where assets will be added. It
     * 		must end with '-discovered-assets'. The first part of the name should
     * 		identify the discovery service using the endpoint
     * @type {string}
     * @memberof DiscoveredAssetsPayload
     */
    groupName: string;
}

/**
 * Check if a given object implements the DiscoveredAssetsPayload interface.
 */
export function instanceOfDiscoveredAssetsPayload(value: object): boolean {
    if (!('groupName' in value)) return false;
    return true;
}

export function DiscoveredAssetsPayloadFromJSON(json: any): DiscoveredAssetsPayload {
    return DiscoveredAssetsPayloadFromJSONTyped(json, false);
}

export function DiscoveredAssetsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveredAssetsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetWithAnnotationsPayloadFromJSON)),
        'groupName': json['group_name'],
    };
}

export function DiscoveredAssetsPayloadToJSON(value?: DiscoveredAssetsPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetWithAnnotationsPayloadToJSON)),
        'group_name': value['groupName'],
    };
}

