/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Statsaverages } from './Statsaverages';
import {
    StatsaveragesFromJSON,
    StatsaveragesFromJSONTyped,
    StatsaveragesToJSON,
} from './Statsaverages';

/**
 * Exposure stats (default view)
 * @export
 * @interface Exposure
 */
export interface Exposure {
    /**
     * 
     * @type {Statsaverages}
     * @memberof Exposure
     */
    exposure?: Statsaverages;
}

/**
 * Check if a given object implements the Exposure interface.
 */
export function instanceOfExposure(value: object): boolean {
    return true;
}

export function ExposureFromJSON(json: any): Exposure {
    return ExposureFromJSONTyped(json, false);
}

export function ExposureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Exposure {
    if (json == null) {
        return json;
    }
    return {
        
        'exposure': json['exposure'] == null ? undefined : StatsaveragesFromJSON(json['exposure']),
    };
}

export function ExposureToJSON(value?: Exposure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exposure': StatsaveragesToJSON(value['exposure']),
    };
}

