/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Finding,
    FindingFromJSON,
    FindingFromJSONTyped,
    FindingToJSON,
} from './Finding';
import {
    Pagination,
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * Findings list (default view)
 * @export
 * @interface FindingsList
 */
export interface FindingsList {
    /**
     * FindingCollection is the media type for an array of Finding (default view)
     * @type {Array<Finding>}
     * @memberof FindingsList
     */
    findings?: Array<Finding>;
    /**
     * 
     * @type {Pagination}
     * @memberof FindingsList
     */
    pagination?: Pagination;
}

export function FindingsListFromJSON(json: any): FindingsList {
    return FindingsListFromJSONTyped(json, false);
}

export function FindingsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'findings': !exists(json, 'findings') ? undefined : ((json['findings'] as Array<any>).map(FindingFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function FindingsListToJSON(value?: FindingsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'findings': value.findings === undefined ? undefined : ((value.findings as Array<any>).map(FindingToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

