/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindingOverwritePayload
 */
export interface FindingOverwritePayload {
    /**
     * Notes
     * @type {string}
     * @memberof FindingOverwritePayload
     */
    notes: string;
    /**
     * Status
     * @type {string}
     * @memberof FindingOverwritePayload
     */
    status: string;
}

/**
 * Check if a given object implements the FindingOverwritePayload interface.
 */
export function instanceOfFindingOverwritePayload(value: object): boolean {
    if (!('notes' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function FindingOverwritePayloadFromJSON(json: any): FindingOverwritePayload {
    return FindingOverwritePayloadFromJSONTyped(json, false);
}

export function FindingOverwritePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingOverwritePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'notes': json['notes'],
        'status': json['status'],
    };
}

export function FindingOverwritePayloadToJSON(value?: FindingOverwritePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'notes': value['notes'],
        'status': value['status'],
    };
}

