/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindingOverridePayload
 */
export interface FindingOverridePayload {
    /**
     * Notes
     * @type {string}
     * @memberof FindingOverridePayload
     */
    notes: string;
    /**
     * Status
     * @type {string}
     * @memberof FindingOverridePayload
     */
    status: string;
}

export function FindingOverridePayloadFromJSON(json: any): FindingOverridePayload {
    return FindingOverridePayloadFromJSONTyped(json, false);
}

export function FindingOverridePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingOverridePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notes': json['notes'],
        'status': json['status'],
    };
}

export function FindingOverridePayloadToJSON(value?: FindingOverridePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notes': value.notes,
        'status': value.status,
    };
}


