/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindingTicketPayload
 */
export interface FindingTicketPayload {
    /**
     * Description
     * @type {string}
     * @memberof FindingTicketPayload
     */
    description?: string;
    /**
     * Jira issue labels
     * @type {Array<string>}
     * @memberof FindingTicketPayload
     */
    labels?: Array<string>;
    /**
     * Summary
     * @type {string}
     * @memberof FindingTicketPayload
     */
    summary: string;
}

/**
 * Check if a given object implements the FindingTicketPayload interface.
 */
export function instanceOfFindingTicketPayload(value: object): boolean {
    if (!('summary' in value)) return false;
    return true;
}

export function FindingTicketPayloadFromJSON(json: any): FindingTicketPayload {
    return FindingTicketPayloadFromJSONTyped(json, false);
}

export function FindingTicketPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingTicketPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'summary': json['summary'],
    };
}

export function FindingTicketPayloadToJSON(value?: FindingTicketPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'labels': value['labels'],
        'summary': value['summary'],
    };
}

