/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Findings Labels (default view)
 * @export
 * @interface FindingsLabels
 */
export interface FindingsLabels {
    /**
     * associated labels
     * @type {Array<string>}
     * @memberof FindingsLabels
     */
    labels?: Array<string>;
}

/**
 * Check if a given object implements the FindingsLabels interface.
 */
export function instanceOfFindingsLabels(value: object): boolean {
    return true;
}

export function FindingsLabelsFromJSON(json: any): FindingsLabels {
    return FindingsLabelsFromJSONTyped(json, false);
}

export function FindingsLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingsLabels {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

export function FindingsLabelsToJSON(value?: FindingsLabels | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'labels': value['labels'],
    };
}

