/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Attachment } from './Attachment';
import {
    AttachmentFromJSON,
    AttachmentFromJSONTyped,
    AttachmentToJSON,
} from './Attachment';
import type { Issue } from './Issue';
import {
    IssueFromJSON,
    IssueFromJSONTyped,
    IssueToJSON,
} from './Issue';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
} from './Resource';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
} from './Source';
import type { Target } from './Target';
import {
    TargetFromJSON,
    TargetFromJSONTyped,
    TargetToJSON,
} from './Target';

/**
 * Finding (default view)
 * @export
 * @interface Finding
 */
export interface Finding {
    /**
     * Affected Resource
     * @type {string}
     * @memberof Finding
     */
    affectedResource?: string;
    /**
     * Attachments
     * @type {Array<Attachment>}
     * @memberof Finding
     */
    attachments?: Array<Attachment>;
    /**
     * Current exposure (hours). Only for OPEN findings
     * @type {number}
     * @memberof Finding
     */
    currentExposure?: number;
    /**
     * Details
     * @type {string}
     * @memberof Finding
     */
    details?: string;
    /**
     * Finding ID
     * @type {string}
     * @memberof Finding
     */
    id?: string;
    /**
     * Impact details
     * @type {string}
     * @memberof Finding
     */
    impactDetails?: string;
    /**
     * 
     * @type {Issue}
     * @memberof Finding
     */
    issue?: Issue;
    /**
     * Resources
     * @type {Array<Resource>}
     * @memberof Finding
     */
    resources?: Array<Resource>;
    /**
     * Score
     * @type {number}
     * @memberof Finding
     */
    score?: number;
    /**
     * 
     * @type {Source}
     * @memberof Finding
     */
    source?: Source;
    /**
     * Status
     * @type {string}
     * @memberof Finding
     */
    status?: string;
    /**
     * 
     * @type {Target}
     * @memberof Finding
     */
    target?: Target;
    /**
     * Total exposure (hours)
     * @type {number}
     * @memberof Finding
     */
    totalExposure?: number;
    /**
     * Link to the ticket
     * @type {string}
     * @memberof Finding
     */
    urlTracker?: string;
}

/**
 * Check if a given object implements the Finding interface.
 */
export function instanceOfFinding(value: object): boolean {
    return true;
}

export function FindingFromJSON(json: any): Finding {
    return FindingFromJSONTyped(json, false);
}

export function FindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Finding {
    if (json == null) {
        return json;
    }
    return {
        
        'affectedResource': json['affected_resource'] == null ? undefined : json['affected_resource'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AttachmentFromJSON)),
        'currentExposure': json['current_exposure'] == null ? undefined : json['current_exposure'],
        'details': json['details'] == null ? undefined : json['details'],
        'id': json['id'] == null ? undefined : json['id'],
        'impactDetails': json['impact_details'] == null ? undefined : json['impact_details'],
        'issue': json['issue'] == null ? undefined : IssueFromJSON(json['issue']),
        'resources': json['resources'] == null ? undefined : ((json['resources'] as Array<any>).map(ResourceFromJSON)),
        'score': json['score'] == null ? undefined : json['score'],
        'source': json['source'] == null ? undefined : SourceFromJSON(json['source']),
        'status': json['status'] == null ? undefined : json['status'],
        'target': json['target'] == null ? undefined : TargetFromJSON(json['target']),
        'totalExposure': json['total_exposure'] == null ? undefined : json['total_exposure'],
        'urlTracker': json['url_tracker'] == null ? undefined : json['url_tracker'],
    };
}

export function FindingToJSON(value?: Finding | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'affected_resource': value['affectedResource'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AttachmentToJSON)),
        'current_exposure': value['currentExposure'],
        'details': value['details'],
        'id': value['id'],
        'impact_details': value['impactDetails'],
        'issue': IssueToJSON(value['issue']),
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(ResourceToJSON)),
        'score': value['score'],
        'source': SourceToJSON(value['source']),
        'status': value['status'],
        'target': TargetToJSON(value['target']),
        'total_exposure': value['totalExposure'],
        'url_tracker': value['urlTracker'],
    };
}

