/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Group (WithoutAssetsCount view)
 * @export
 * @interface GroupWithoutAssetsCount
 */
export interface GroupWithoutAssetsCount {
    /**
     * Description
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    description?: string;
    /**
     * Group ID
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    name?: string;
    /**
     * Options
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    options?: string;
}

export function GroupWithoutAssetsCountFromJSON(json: any): GroupWithoutAssetsCount {
    return GroupWithoutAssetsCountFromJSONTyped(json, false);
}

export function GroupWithoutAssetsCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupWithoutAssetsCount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'options': !exists(json, 'options') ? undefined : json['options'],
    };
}

export function GroupWithoutAssetsCountToJSON(value?: GroupWithoutAssetsCount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'id': value.id,
        'name': value.name,
        'options': value.options,
    };
}


