/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupPayload
 */
export interface GroupPayload {
    /**
     * name
     * @type {string}
     * @memberof GroupPayload
     */
    name: string;
    /**
     * Options
     * @type {string}
     * @memberof GroupPayload
     */
    options?: string;
}

export function GroupPayloadFromJSON(json: any): GroupPayload {
    return GroupPayloadFromJSONTyped(json, false);
}

export function GroupPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'options': !exists(json, 'options') ? undefined : json['options'],
    };
}

export function GroupPayloadToJSON(value?: GroupPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'options': value.options,
    };
}


