/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Group (WithoutAssetsCount view)
 * @export
 * @interface GroupWithoutAssetsCount
 */
export interface GroupWithoutAssetsCount {
    /**
     * Description
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    description?: string;
    /**
     * Group ID
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    name?: string;
    /**
     * Options
     * @type {string}
     * @memberof GroupWithoutAssetsCount
     */
    options?: string;
}

/**
 * Check if a given object implements the GroupWithoutAssetsCount interface.
 */
export function instanceOfGroupWithoutAssetsCount(value: object): boolean {
    return true;
}

export function GroupWithoutAssetsCountFromJSON(json: any): GroupWithoutAssetsCount {
    return GroupWithoutAssetsCountFromJSONTyped(json, false);
}

export function GroupWithoutAssetsCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupWithoutAssetsCount {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function GroupWithoutAssetsCountToJSON(value?: GroupWithoutAssetsCount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'options': value['options'],
    };
}

