/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Issue (default view)
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * Common Weakness Enumeration ID
     * @type {number}
     * @memberof Issue
     */
    cweId?: number;
    /**
     * Issue description
     * @type {string}
     * @memberof Issue
     */
    description?: string;
    /**
     * Issue ID
     * @type {string}
     * @memberof Issue
     */
    id?: string;
    /**
     * Recommendations to fix the issue
     * @type {Array<string>}
     * @memberof Issue
     */
    recommendations?: Array<string>;
    /**
     * Documentation reference for the issue
     * @type {Array<string>}
     * @memberof Issue
     */
    referenceLinks?: Array<string>;
    /**
     * Issue summary
     * @type {string}
     * @memberof Issue
     */
    summary?: string;
}

export function IssueFromJSON(json: any): Issue {
    return IssueFromJSONTyped(json, false);
}

export function IssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Issue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cweId': !exists(json, 'cwe_id') ? undefined : json['cwe_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'recommendations': !exists(json, 'recommendations') ? undefined : json['recommendations'],
        'referenceLinks': !exists(json, 'reference_links') ? undefined : json['reference_links'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
    };
}

export function IssueToJSON(value?: Issue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cwe_id': value.cweId,
        'description': value.description,
        'id': value.id,
        'recommendations': value.recommendations,
        'reference_links': value.referenceLinks,
        'summary': value.summary,
    };
}


