/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Assettype } from './Assettype';
import {
    AssettypeFromJSON,
    AssettypeFromJSONTyped,
    AssettypeToJSON,
} from './Assettype';
import type { GroupWithoutAssetsCount } from './GroupWithoutAssetsCount';
import {
    GroupWithoutAssetsCountFromJSON,
    GroupWithoutAssetsCountFromJSONTyped,
    GroupWithoutAssetsCountToJSON,
} from './GroupWithoutAssetsCount';

/**
 * List Asset Entry (default view)
 * @export
 * @interface Listassetentry
 */
export interface Listassetentry {
    /**
     * Alias
     * @type {string}
     * @memberof Listassetentry
     */
    alias?: string;
    /**
     * 
     * @type {object}
     * @memberof Listassetentry
     */
    annotations?: object;
    /**
     * Classified At
     * @type {string}
     * @memberof Listassetentry
     */
    classifiedAt?: string;
    /**
     * Environmental CVSS
     * @type {string}
     * @memberof Listassetentry
     */
    environmentalCvss?: string;
    /**
     * GroupWithoutAssetsCountCollection is the media type for an array of GroupWithoutAssetsCount (default view)
     * @type {Array<GroupWithoutAssetsCount>}
     * @memberof Listassetentry
     */
    groups?: Array<GroupWithoutAssetsCount>;
    /**
     * Asset ID
     * @type {string}
     * @memberof Listassetentry
     */
    id?: string;
    /**
     * Identifier
     * @type {string}
     * @memberof Listassetentry
     */
    identifier?: string;
    /**
     * Options
     * @type {string}
     * @memberof Listassetentry
     */
    options?: string;
    /**
     * Rolfp plus scope vector
     * @type {string}
     * @memberof Listassetentry
     */
    rolfp?: string;
    /**
     * Scannable
     * @type {boolean}
     * @memberof Listassetentry
     */
    scannable?: boolean;
    /**
     * 
     * @type {Assettype}
     * @memberof Listassetentry
     */
    type?: Assettype;
}

/**
 * Check if a given object implements the Listassetentry interface.
 */
export function instanceOfListassetentry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListassetentryFromJSON(json: any): Listassetentry {
    return ListassetentryFromJSONTyped(json, false);
}

export function ListassetentryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Listassetentry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'annotations': !exists(json, 'annotations') ? undefined : json['annotations'],
        'classifiedAt': !exists(json, 'classified_at') ? undefined : json['classified_at'],
        'environmentalCvss': !exists(json, 'environmental_cvss') ? undefined : json['environmental_cvss'],
        'groups': !exists(json, 'groups') ? undefined : ((json['groups'] as Array<any>).map(GroupWithoutAssetsCountFromJSON)),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'options': !exists(json, 'options') ? undefined : json['options'],
        'rolfp': !exists(json, 'rolfp') ? undefined : json['rolfp'],
        'scannable': !exists(json, 'scannable') ? undefined : json['scannable'],
        'type': !exists(json, 'type') ? undefined : AssettypeFromJSON(json['type']),
    };
}

export function ListassetentryToJSON(value?: Listassetentry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'annotations': value.annotations,
        'classified_at': value.classifiedAt,
        'environmental_cvss': value.environmentalCvss,
        'groups': value.groups === undefined ? undefined : ((value.groups as Array<any>).map(GroupWithoutAssetsCountToJSON)),
        'id': value.id,
        'identifier': value.identifier,
        'options': value.options,
        'rolfp': value.rolfp,
        'scannable': value.scannable,
        'type': AssettypeToJSON(value.type),
    };
}

