/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error (default view)
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Code
     * @type {number}
     * @memberof ModelError
     */
    code: number;
    /**
     * Error
     * @type {string}
     * @memberof ModelError
     */
    error: string;
    /**
     * Type
     * @type {string}
     * @memberof ModelError
     */
    type: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('error' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'error': json['error'],
        'type': json['type'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'error': value['error'],
        'type': value['type'],
    };
}

