/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Statstotal,
    StatstotalFromJSON,
    StatstotalFromJSONTyped,
    StatstotalToJSON,
} from './';

/**
 * MTTR stats (default view)
 * @export
 * @interface Mttr
 */
export interface Mttr {
    /**
     * 
     * @type {Statstotal}
     * @memberof Mttr
     */
    mttr?: Statstotal;
}

export function MttrFromJSON(json: any): Mttr {
    return MttrFromJSONTyped(json, false);
}

export function MttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mttr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mttr': !exists(json, 'mttr') ? undefined : StatstotalFromJSON(json['mttr']),
    };
}

export function MttrToJSON(value?: Mttr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mttr': StatstotalToJSON(value.mttr),
    };
}


