/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination info (default view)
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * Limit of results for the list
     * @type {number}
     * @memberof Pagination
     */
    limit?: number;
    /**
     * Indicates if there are more results to query for the list
     * @type {boolean}
     * @memberof Pagination
     */
    more?: boolean;
    /**
     * Results list offset
     * @type {number}
     * @memberof Pagination
     */
    offset?: number;
    /**
     * Total number of results for the list
     * @type {number}
     * @memberof Pagination
     */
    total?: number;
}

/**
 * Check if a given object implements the Pagination interface.
 */
export function instanceOfPagination(value: object): boolean {
    return true;
}

export function PaginationFromJSON(json: any): Pagination {
    return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'more': json['more'] == null ? undefined : json['more'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PaginationToJSON(value?: Pagination | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'limit': value['limit'],
        'more': value['more'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

