/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicySettingPayload
 */
export interface PolicySettingPayload {
    /**
     * Check Type Name
     * @type {string}
     * @memberof PolicySettingPayload
     */
    checktypeName: string;
    /**
     * Options
     * @type {string}
     * @memberof PolicySettingPayload
     */
    options?: string;
}

export function PolicySettingPayloadFromJSON(json: any): PolicySettingPayload {
    return PolicySettingPayloadFromJSONTyped(json, false);
}

export function PolicySettingPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicySettingPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checktypeName': json['checktype_name'],
        'options': !exists(json, 'options') ? undefined : json['options'],
    };
}

export function PolicySettingPayloadToJSON(value?: PolicySettingPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checktype_name': value.checktypeName,
        'options': value.options,
    };
}

