/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicyUpdatePayload
 */
export interface PolicyUpdatePayload {
    /**
     * name
     * @type {string}
     * @memberof PolicyUpdatePayload
     */
    name?: string;
}

/**
 * Check if a given object implements the PolicyUpdatePayload interface.
 */
export function instanceOfPolicyUpdatePayload(value: object): boolean {
    return true;
}

export function PolicyUpdatePayloadFromJSON(json: any): PolicyUpdatePayload {
    return PolicyUpdatePayloadFromJSONTyped(json, false);
}

export function PolicyUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyUpdatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PolicyUpdatePayloadToJSON(value?: PolicyUpdatePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

