/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Policy (default view)
 * @export
 * @interface Policy
 */
export interface Policy {
    /**
     * Policy ID
     * @type {string}
     * @memberof Policy
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Policy
     */
    name?: string;
    /**
     * Policy settings count
     * @type {number}
     * @memberof Policy
     */
    settingsCount?: number;
}

export function PolicyFromJSON(json: any): Policy {
    return PolicyFromJSONTyped(json, false);
}

export function PolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Policy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'settingsCount': !exists(json, 'settings_count') ? undefined : json['settings_count'],
    };
}

export function PolicyToJSON(value?: Policy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'settings_count': value.settingsCount,
    };
}

