/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Policy (default view)
 * @export
 * @interface Policy
 */
export interface Policy {
    /**
     * Policy ID
     * @type {string}
     * @memberof Policy
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Policy
     */
    name?: string;
    /**
     * Policy settings count
     * @type {number}
     * @memberof Policy
     */
    settingsCount?: number;
}

/**
 * Check if a given object implements the Policy interface.
 */
export function instanceOfPolicy(value: object): boolean {
    return true;
}

export function PolicyFromJSON(json: any): Policy {
    return PolicyFromJSONTyped(json, false);
}

export function PolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Policy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'settingsCount': json['settings_count'] == null ? undefined : json['settings_count'],
    };
}

export function PolicyToJSON(value?: Policy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'settings_count': value['settingsCount'],
    };
}

