/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProgramPolicyGroupPayload } from './ProgramPolicyGroupPayload';
import {
    ProgramPolicyGroupPayloadFromJSON,
    ProgramPolicyGroupPayloadFromJSONTyped,
    ProgramPolicyGroupPayloadToJSON,
} from './ProgramPolicyGroupPayload';

/**
 * 
 * @export
 * @interface ProgramUpdatePayload
 */
export interface ProgramUpdatePayload {
    /**
     * Autosend
     * @type {boolean}
     * @memberof ProgramUpdatePayload
     */
    autosend?: boolean;
    /**
     * Disabled
     * @type {boolean}
     * @memberof ProgramUpdatePayload
     */
    disabled?: boolean;
    /**
     * name
     * @type {string}
     * @memberof ProgramUpdatePayload
     */
    name?: string;
    /**
     * PolicyGroups
     * @type {Array<ProgramPolicyGroupPayload>}
     * @memberof ProgramUpdatePayload
     */
    policyGroups?: Array<ProgramPolicyGroupPayload>;
}

/**
 * Check if a given object implements the ProgramUpdatePayload interface.
 */
export function instanceOfProgramUpdatePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProgramUpdatePayloadFromJSON(json: any): ProgramUpdatePayload {
    return ProgramUpdatePayloadFromJSONTyped(json, false);
}

export function ProgramUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramUpdatePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'autosend': !exists(json, 'autosend') ? undefined : json['autosend'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'policyGroups': !exists(json, 'policy_groups') ? undefined : ((json['policy_groups'] as Array<any>).map(ProgramPolicyGroupPayloadFromJSON)),
    };
}

export function ProgramUpdatePayloadToJSON(value?: ProgramUpdatePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'autosend': value.autosend,
        'disabled': value.disabled,
        'name': value.name,
        'policy_groups': value.policyGroups === undefined ? undefined : ((value.policyGroups as Array<any>).map(ProgramPolicyGroupPayloadToJSON)),
    };
}

