/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Group,
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    Policy,
    PolicyFromJSON,
    PolicyFromJSONTyped,
    PolicyToJSON,
} from './';

/**
 * Program_policy_group media type (default view)
 * @export
 * @interface ProgramPolicyGroup
 */
export interface ProgramPolicyGroup {
    /**
     * 
     * @type {Group}
     * @memberof ProgramPolicyGroup
     */
    group?: Group;
    /**
     * 
     * @type {Policy}
     * @memberof ProgramPolicyGroup
     */
    policy?: Policy;
}

export function ProgramPolicyGroupFromJSON(json: any): ProgramPolicyGroup {
    return ProgramPolicyGroupFromJSONTyped(json, false);
}

export function ProgramPolicyGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramPolicyGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': !exists(json, 'group') ? undefined : GroupFromJSON(json['group']),
        'policy': !exists(json, 'policy') ? undefined : PolicyFromJSON(json['policy']),
    };
}

export function ProgramPolicyGroupToJSON(value?: ProgramPolicyGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': GroupToJSON(value.group),
        'policy': PolicyToJSON(value.policy),
    };
}


