/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProgramPolicyGroupPayload
 */
export interface ProgramPolicyGroupPayload {
    /**
     * group
     * @type {string}
     * @memberof ProgramPolicyGroupPayload
     */
    groupId?: string;
    /**
     * policy
     * @type {string}
     * @memberof ProgramPolicyGroupPayload
     */
    policyId?: string;
}

export function ProgramPolicyGroupPayloadFromJSON(json: any): ProgramPolicyGroupPayload {
    return ProgramPolicyGroupPayloadFromJSONTyped(json, false);
}

export function ProgramPolicyGroupPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramPolicyGroupPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': !exists(json, 'group_id') ? undefined : json['group_id'],
        'policyId': !exists(json, 'policy_id') ? undefined : json['policy_id'],
    };
}

export function ProgramPolicyGroupPayloadToJSON(value?: ProgramPolicyGroupPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_id': value.groupId,
        'policy_id': value.policyId,
    };
}


