/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProgramPolicyGroup } from './ProgramPolicyGroup';
import {
    ProgramPolicyGroupFromJSON,
    ProgramPolicyGroupFromJSONTyped,
    ProgramPolicyGroupToJSON,
} from './ProgramPolicyGroup';
import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
} from './Schedule';

/**
 * Program (default view)
 * @export
 * @interface Program
 */
export interface Program {
    /**
     * Autosend
     * @type {boolean}
     * @memberof Program
     */
    autosend?: boolean;
    /**
     * Disabled
     * @type {boolean}
     * @memberof Program
     */
    disabled?: boolean;
    /**
     * Global
     * @type {boolean}
     * @memberof Program
     */
    global?: boolean;
    /**
     * Program ID
     * @type {string}
     * @memberof Program
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Program
     */
    name?: string;
    /**
     * PolicyGroup
     * @type {Array<ProgramPolicyGroup>}
     * @memberof Program
     */
    policyGroups?: Array<ProgramPolicyGroup>;
    /**
     * 
     * @type {Schedule}
     * @memberof Program
     */
    schedule?: Schedule;
}

/**
 * Check if a given object implements the Program interface.
 */
export function instanceOfProgram(value: object): boolean {
    return true;
}

export function ProgramFromJSON(json: any): Program {
    return ProgramFromJSONTyped(json, false);
}

export function ProgramFromJSONTyped(json: any, ignoreDiscriminator: boolean): Program {
    if (json == null) {
        return json;
    }
    return {
        
        'autosend': json['autosend'] == null ? undefined : json['autosend'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'global': json['global'] == null ? undefined : json['global'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'policyGroups': json['policy_groups'] == null ? undefined : ((json['policy_groups'] as Array<any>).map(ProgramPolicyGroupFromJSON)),
        'schedule': json['schedule'] == null ? undefined : ScheduleFromJSON(json['schedule']),
    };
}

export function ProgramToJSON(value?: Program | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'autosend': value['autosend'],
        'disabled': value['disabled'],
        'global': value['global'],
        'id': value['id'],
        'name': value['name'],
        'policy_groups': value['policyGroups'] == null ? undefined : ((value['policyGroups'] as Array<any>).map(ProgramPolicyGroupToJSON)),
        'schedule': ScheduleToJSON(value['schedule']),
    };
}

