/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProgramPolicyGroupPayload } from './ProgramPolicyGroupPayload';
import {
    ProgramPolicyGroupPayloadFromJSON,
    ProgramPolicyGroupPayloadFromJSONTyped,
    ProgramPolicyGroupPayloadToJSON,
} from './ProgramPolicyGroupPayload';

/**
 * 
 * @export
 * @interface ProgramPayload
 */
export interface ProgramPayload {
    /**
     * Autosend
     * @type {boolean}
     * @memberof ProgramPayload
     */
    autosend?: boolean;
    /**
     * Disabled
     * @type {boolean}
     * @memberof ProgramPayload
     */
    disabled?: boolean;
    /**
     * name
     * @type {string}
     * @memberof ProgramPayload
     */
    name?: string;
    /**
     * PolicyGroups
     * @type {Array<ProgramPolicyGroupPayload>}
     * @memberof ProgramPayload
     */
    policyGroups?: Array<ProgramPolicyGroupPayload>;
}

/**
 * Check if a given object implements the ProgramPayload interface.
 */
export function instanceOfProgramPayload(value: object): boolean {
    return true;
}

export function ProgramPayloadFromJSON(json: any): ProgramPayload {
    return ProgramPayloadFromJSONTyped(json, false);
}

export function ProgramPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'autosend': json['autosend'] == null ? undefined : json['autosend'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'name': json['name'] == null ? undefined : json['name'],
        'policyGroups': json['policy_groups'] == null ? undefined : ((json['policy_groups'] as Array<any>).map(ProgramPolicyGroupPayloadFromJSON)),
    };
}

export function ProgramPayloadToJSON(value?: ProgramPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'autosend': value['autosend'],
        'disabled': value['disabled'],
        'name': value['name'],
        'policy_groups': value['policyGroups'] == null ? undefined : ((value['policyGroups'] as Array<any>).map(ProgramPolicyGroupPayloadToJSON)),
    };
}

