/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Report (default view)
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * Delivered To
     * @type {string}
     * @memberof Report
     */
    deliveredTo?: string;
    /**
     * Report ID
     * @type {string}
     * @memberof Report
     */
    id?: string;
    /**
     * Report URL
     * @type {string}
     * @memberof Report
     */
    report?: string;
    /**
     * Report JSON URL
     * @type {string}
     * @memberof Report
     */
    reportJson?: string;
    /**
     * Scan ID
     * @type {string}
     * @memberof Report
     */
    scanId?: string;
    /**
     * Status
     * @type {string}
     * @memberof Report
     */
    status?: string;
}

export function ReportFromJSON(json: any): Report {
    return ReportFromJSONTyped(json, false);
}

export function ReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deliveredTo': !exists(json, 'delivered_to') ? undefined : json['delivered_to'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'report': !exists(json, 'report') ? undefined : json['report'],
        'reportJson': !exists(json, 'report_json') ? undefined : json['report_json'],
        'scanId': !exists(json, 'scan_id') ? undefined : json['scan_id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ReportToJSON(value?: Report | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delivered_to': value.deliveredTo,
        'id': value.id,
        'report': value.report,
        'report_json': value.reportJson,
        'scan_id': value.scanId,
        'status': value.status,
    };
}

