/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Report Email Body (default view)
 * @export
 * @interface Reportemail
 */
export interface Reportemail {
    /**
     * Email Body
     * @type {string}
     * @memberof Reportemail
     */
    emailBody?: string;
}

/**
 * Check if a given object implements the Reportemail interface.
 */
export function instanceOfReportemail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReportemailFromJSON(json: any): Reportemail {
    return ReportemailFromJSONTyped(json, false);
}

export function ReportemailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reportemail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailBody': !exists(json, 'email_body') ? undefined : json['email_body'],
    };
}

export function ReportemailToJSON(value?: Reportemail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email_body': value.emailBody,
    };
}

