/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * resource (default view)
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * attributes of a resource
     * @type {Array<string>}
     * @memberof Resource
     */
    attributes?: Array<string>;
    /**
     * Resource name
     * @type {string}
     * @memberof Resource
     */
    name?: string;
    /**
     * values for attributes of a resource
     * @type {Array<{ [key: string]: any; }>}
     * @memberof Resource
     */
    resources?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the Resource interface.
 */
export function instanceOfResource(value: object): boolean {
    return true;
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'name': json['name'] == null ? undefined : json['name'],
        'resources': json['resources'] == null ? undefined : json['resources'],
    };
}

export function ResourceToJSON(value?: Resource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attributes': value['attributes'],
        'name': value['name'],
        'resources': value['resources'],
    };
}

