/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * resource (default view)
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * attributes of a resource
     * @type {Array<string>}
     * @memberof Resource
     */
    attributes?: Array<string>;
    /**
     * Resource name
     * @type {string}
     * @memberof Resource
     */
    name?: string;
    /**
     * values for attributes of a resource
     * @type {Array<object>}
     * @memberof Resource
     */
    resources?: Array<object>;
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'resources': !exists(json, 'resources') ? undefined : json['resources'],
    };
}

export function ResourceToJSON(value?: Resource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': value.attributes,
        'name': value.name,
        'resources': value.resources,
    };
}


