/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schedule (default view)
 * @export
 * @interface Schedule
 */
export interface Schedule {
    /**
     * Cron Expression
     * @type {string}
     * @memberof Schedule
     */
    cron: string;
}

/**
 * Check if a given object implements the Schedule interface.
 */
export function instanceOfSchedule(value: object): boolean {
    if (!('cron' in value)) return false;
    return true;
}

export function ScheduleFromJSON(json: any): Schedule {
    return ScheduleFromJSONTyped(json, false);
}

export function ScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Schedule {
    if (json == null) {
        return json;
    }
    return {
        
        'cron': json['cron'],
    };
}

export function ScheduleToJSON(value?: Schedule | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cron': value['cron'],
    };
}

