/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stats } from './Stats';
import {
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './Stats';

/**
 * Open issues stats (default view)
 * @export
 * @interface Statsopen
 */
export interface Statsopen {
    /**
     * 
     * @type {Stats}
     * @memberof Statsopen
     */
    openIssues?: Stats;
}

/**
 * Check if a given object implements the Statsopen interface.
 */
export function instanceOfStatsopen(value: object): boolean {
    return true;
}

export function StatsopenFromJSON(json: any): Statsopen {
    return StatsopenFromJSONTyped(json, false);
}

export function StatsopenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statsopen {
    if (json == null) {
        return json;
    }
    return {
        
        'openIssues': json['open_issues'] == null ? undefined : StatsFromJSON(json['open_issues']),
    };
}

export function StatsopenToJSON(value?: Statsopen | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'open_issues': StatsToJSON(value['openIssues']),
    };
}

