/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stats by severity (default view)
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * Stats for critical vulnerabilities
     * @type {number}
     * @memberof Stats
     */
    critical?: number;
    /**
     * Stats for high vulnerabilities
     * @type {number}
     * @memberof Stats
     */
    high?: number;
    /**
     * Stats for informational vulnerabilities
     * @type {number}
     * @memberof Stats
     */
    informational?: number;
    /**
     * Stats for low vulnerabilities
     * @type {number}
     * @memberof Stats
     */
    low?: number;
    /**
     * Stats for medium vulnerabilities
     * @type {number}
     * @memberof Stats
     */
    medium?: number;
}

/**
 * Check if a given object implements the Stats interface.
 */
export function instanceOfStats(value: object): boolean {
    return true;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if (json == null) {
        return json;
    }
    return {
        
        'critical': json['critical'] == null ? undefined : json['critical'],
        'high': json['high'] == null ? undefined : json['high'],
        'informational': json['informational'] == null ? undefined : json['informational'],
        'low': json['low'] == null ? undefined : json['low'],
        'medium': json['medium'] == null ? undefined : json['medium'],
    };
}

export function StatsToJSON(value?: Stats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'critical': value['critical'],
        'high': value['high'],
        'informational': value['informational'],
        'low': value['low'],
        'medium': value['medium'],
    };
}

