/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Asset Coverage: discovered vs. confirmed (default view)
 * @export
 * @interface Statscoverage
 */
export interface Statscoverage {
    /**
     * Percentage of assets confirmed respect to discovered
     * @type {number}
     * @memberof Statscoverage
     */
    coverage?: number;
}

/**
 * Check if a given object implements the Statscoverage interface.
 */
export function instanceOfStatscoverage(value: object): boolean {
    return true;
}

export function StatscoverageFromJSON(json: any): Statscoverage {
    return StatscoverageFromJSONTyped(json, false);
}

export function StatscoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statscoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'coverage': json['coverage'] == null ? undefined : json['coverage'],
    };
}

export function StatscoverageToJSON(value?: Statscoverage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coverage': value['coverage'],
    };
}

