/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Stats by different averages (default view)
 * @export
 * @interface Statsaverages
 */
export interface Statsaverages {
    /**
     * Mean of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    mean?: number;
    /**
     * Percentile 10 of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    percentile10?: number;
    /**
     * Percentile 25 of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    percentile25?: number;
    /**
     * Percentile 50 or median of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    percentile50?: number;
    /**
     * Percentile 75 or third quartile of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    percentile75?: number;
    /**
     * Percentile 90 of the stats
     * @type {number}
     * @memberof Statsaverages
     */
    percentile90?: number;
}

/**
 * Check if a given object implements the Statsaverages interface.
 */
export function instanceOfStatsaverages(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatsaveragesFromJSON(json: any): Statsaverages {
    return StatsaveragesFromJSONTyped(json, false);
}

export function StatsaveragesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statsaverages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mean': !exists(json, 'mean') ? undefined : json['mean'],
        'percentile10': !exists(json, 'percentile_10') ? undefined : json['percentile_10'],
        'percentile25': !exists(json, 'percentile_25') ? undefined : json['percentile_25'],
        'percentile50': !exists(json, 'percentile_50') ? undefined : json['percentile_50'],
        'percentile75': !exists(json, 'percentile_75') ? undefined : json['percentile_75'],
        'percentile90': !exists(json, 'percentile_90') ? undefined : json['percentile_90'],
    };
}

export function StatsaveragesToJSON(value?: Statsaverages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mean': value.mean,
        'percentile_10': value.percentile10,
        'percentile_25': value.percentile25,
        'percentile_50': value.percentile50,
        'percentile_75': value.percentile75,
        'percentile_90': value.percentile90,
    };
}

