/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Stats,
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './';

/**
 * Open issues stats (default view)
 * @export
 * @interface Statsopen
 */
export interface Statsopen {
    /**
     * 
     * @type {Stats}
     * @memberof Statsopen
     */
    openIssues?: Stats;
}

export function StatsopenFromJSON(json: any): Statsopen {
    return StatsopenFromJSONTyped(json, false);
}

export function StatsopenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statsopen {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'openIssues': !exists(json, 'open_issues') ? undefined : StatsFromJSON(json['open_issues']),
    };
}

export function StatsopenToJSON(value?: Statsopen | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'open_issues': StatsToJSON(value.openIssues),
    };
}


