/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * Team Member (default view)
 * @export
 * @interface Teammember
 */
export interface Teammember {
    /**
     * Role
     * @type {string}
     * @memberof Teammember
     */
    role?: string;
    /**
     * 
     * @type {User}
     * @memberof Teammember
     */
    user?: User;
}

export function TeammemberFromJSON(json: any): Teammember {
    return TeammemberFromJSONTyped(json, false);
}

export function TeammemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): Teammember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function TeammemberToJSON(value?: Teammember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'user': UserToJSON(value.user),
    };
}


