/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamPayload
 */
export interface TeamPayload {
    /**
     * description
     * @type {string}
     * @memberof TeamPayload
     */
    description?: string;
    /**
     * name
     * @type {string}
     * @memberof TeamPayload
     */
    name: string;
    /**
     * tag
     * @type {string}
     * @memberof TeamPayload
     */
    tag: string;
}

/**
 * Check if a given object implements the TeamPayload interface.
 */
export function instanceOfTeamPayload(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('tag' in value)) return false;
    return true;
}

export function TeamPayloadFromJSON(json: any): TeamPayload {
    return TeamPayloadFromJSONTyped(json, false);
}

export function TeamPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'tag': json['tag'],
    };
}

export function TeamPayloadToJSON(value?: TeamPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
        'tag': value['tag'],
    };
}

