/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Team (default view)
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * Description
     * @type {string}
     * @memberof Team
     */
    description?: string;
    /**
     * Team ID
     * @type {string}
     * @memberof Team
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof Team
     */
    name?: string;
    /**
     * tag
     * @type {string}
     * @memberof Team
     */
    tag?: string;
    /**
     * If the team is Onboarded in Vulcan Tracker
     * @type {boolean}
     * @memberof Team
     */
    usingTracker?: boolean;
}

/**
 * Check if a given object implements the Team interface.
 */
export function instanceOfTeam(value: object): boolean {
    return true;
}

export function TeamFromJSON(json: any): Team {
    return TeamFromJSONTyped(json, false);
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'usingTracker': json['using_tracker'] == null ? undefined : json['using_tracker'],
    };
}

export function TeamToJSON(value?: Team | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'tag': value['tag'],
        'using_tracker': value['usingTracker'],
    };
}

