/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamUpdatePayload
 */
export interface TeamUpdatePayload {
    /**
     * description
     * @type {string}
     * @memberof TeamUpdatePayload
     */
    description?: string;
    /**
     * name
     * @type {string}
     * @memberof TeamUpdatePayload
     */
    name?: string;
    /**
     * tag
     * @type {string}
     * @memberof TeamUpdatePayload
     */
    tag?: string;
}

export function TeamUpdatePayloadFromJSON(json: any): TeamUpdatePayload {
    return TeamUpdatePayloadFromJSONTyped(json, false);
}

export function TeamUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUpdatePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
    };
}

export function TeamUpdatePayloadToJSON(value?: TeamUpdatePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'tag': value.tag,
    };
}

