/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamPayload
 */
export interface TeamPayload {
    /**
     * description
     * @type {string}
     * @memberof TeamPayload
     */
    description?: string;
    /**
     * name
     * @type {string}
     * @memberof TeamPayload
     */
    name: string;
    /**
     * tag
     * @type {string}
     * @memberof TeamPayload
     */
    tag: string;
}

export function TeamPayloadFromJSON(json: any): TeamPayload {
    return TeamPayloadFromJSONTyped(json, false);
}

export function TeamPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'tag': json['tag'],
    };
}

export function TeamPayloadToJSON(value?: TeamPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'tag': value.tag,
    };
}

