/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token (default view)
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * Creation time
     * @type {string}
     * @memberof Token
     */
    creationTime?: string;
    /**
     * Email
     * @type {string}
     * @memberof Token
     */
    email?: string;
    /**
     * Hash
     * @type {string}
     * @memberof Token
     */
    hash?: string;
    /**
     * Token
     * @type {string}
     * @memberof Token
     */
    token?: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): boolean {
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'creationTime': json['creation_time'] == null ? undefined : json['creation_time'],
        'email': json['email'] == null ? undefined : json['email'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'creation_time': value['creationTime'],
        'email': value['email'],
        'hash': value['hash'],
        'token': value['token'],
    };
}

