/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User (default view)
 * @export
 * @interface User
 */
export interface User {
    /**
     * Active
     * @type {boolean}
     * @memberof User
     */
    active?: boolean;
    /**
     * Admin
     * @type {boolean}
     * @memberof User
     */
    admin?: boolean;
    /**
     * Email
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * First name
     * @type {string}
     * @memberof User
     */
    firstname?: string;
    /**
     * User ID
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * last_login
     * @type {Date}
     * @memberof User
     */
    lastLogin?: Date;
    /**
     * Last name
     * @type {string}
     * @memberof User
     */
    lastname?: string;
    /**
     * Observer
     * @type {boolean}
     * @memberof User
     */
    observer?: boolean;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'admin': json['admin'] == null ? undefined : json['admin'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'observer': json['observer'] == null ? undefined : json['observer'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'active': value['active'],
        'admin': value['admin'],
        'email': value['email'],
        'firstname': value['firstname'],
        'id': value['id'],
        'last_login': value['lastLogin'] == null ? undefined : ((value['lastLogin']).toISOString()),
        'lastname': value['lastname'],
        'observer': value['observer'],
    };
}

