/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPayload
 */
export interface UserPayload {
    /**
     * Active (Default: true)
     * @type {boolean}
     * @memberof UserPayload
     */
    active?: boolean;
    /**
     * Admin
     * @type {boolean}
     * @memberof UserPayload
     */
    admin?: boolean;
    /**
     * Email
     * @type {string}
     * @memberof UserPayload
     */
    email: string;
    /**
     * First Name
     * @type {string}
     * @memberof UserPayload
     */
    firstname?: string;
    /**
     * Last Name
     * @type {string}
     * @memberof UserPayload
     */
    lastname?: string;
    /**
     * Observer
     * @type {boolean}
     * @memberof UserPayload
     */
    observer?: boolean;
}

export function UserPayloadFromJSON(json: any): UserPayload {
    return UserPayloadFromJSONTyped(json, false);
}

export function UserPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'admin': !exists(json, 'admin') ? undefined : json['admin'],
        'email': json['email'],
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
        'observer': !exists(json, 'observer') ? undefined : json['observer'],
    };
}

export function UserPayloadToJSON(value?: UserPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'admin': value.admin,
        'email': value.email,
        'firstname': value.firstname,
        'lastname': value.lastname,
        'observer': value.observer,
    };
}

