/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdatePayload
 */
export interface UserUpdatePayload {
    /**
     * Active (Default: true)
     * @type {boolean}
     * @memberof UserUpdatePayload
     */
    active?: boolean;
    /**
     * Admin
     * @type {boolean}
     * @memberof UserUpdatePayload
     */
    admin?: boolean;
    /**
     * First Name
     * @type {string}
     * @memberof UserUpdatePayload
     */
    firstname?: string;
    /**
     * Last Name
     * @type {string}
     * @memberof UserUpdatePayload
     */
    lastname?: string;
}

/**
 * Check if a given object implements the UserUpdatePayload interface.
 */
export function instanceOfUserUpdatePayload(value: object): boolean {
    return true;
}

export function UserUpdatePayloadFromJSON(json: any): UserUpdatePayload {
    return UserUpdatePayloadFromJSONTyped(json, false);
}

export function UserUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'admin': json['admin'] == null ? undefined : json['admin'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
    };
}

export function UserUpdatePayloadToJSON(value?: UserUpdatePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'active': value['active'],
        'admin': value['admin'],
        'firstname': value['firstname'],
        'lastname': value['lastname'],
    };
}

