dist: bionic
language: node_js
node_js: "9"
services:
  - docker
env:
  global:
    # Disable linter warning as errors.
    - CI=false
cache:
  npm: false
install: _script/bootstrap
script: _script/cibuild
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
