/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Token,
    TokenFromJSON,
    TokenToJSON,
} from '../models';

export interface ApiTokenCreateRequest {
    userId: string;
}

/**
 * 
 */
export class ApiTokenApi extends runtime.BaseAPI {

    /**
     * Generate an API token for an user.
     * create api-token
     */
    async apiTokenCreateRaw(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiTokenCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/users/{user_id}/token`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Generate an API token for an user.
     * create api-token
     */
    async apiTokenCreate(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit): Promise<Token> {
        const response = await this.apiTokenCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
