/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Finding,
  FindingOverwrite,
  FindingOverwritePayload,
  FindingTicketCreationPayload,
  FindingTicketcreation,
  FindingsIssuesList,
  FindingsLabels,
  FindingsList,
  FindingsTargetsList,
} from '../models';
import {
    FindingFromJSON,
    FindingToJSON,
    FindingOverwriteFromJSON,
    FindingOverwriteToJSON,
    FindingOverwritePayloadFromJSON,
    FindingOverwritePayloadToJSON,
    FindingTicketCreationPayloadFromJSON,
    FindingTicketCreationPayloadToJSON,
    FindingTicketcreationFromJSON,
    FindingTicketcreationToJSON,
    FindingsIssuesListFromJSON,
    FindingsIssuesListToJSON,
    FindingsLabelsFromJSON,
    FindingsLabelsToJSON,
    FindingsListFromJSON,
    FindingsListToJSON,
    FindingsTargetsListFromJSON,
    FindingsTargetsListToJSON,
} from '../models';

export interface FindingsFindFindingRequest {
    findingId: string;
    teamId: string;
}

export interface FindingsFindFindingsFromAIssueRequest {
    issueId: string;
    teamId: string;
    atDate?: string;
    identifiers?: string;
    labels?: string;
    maxDate?: string;
    maxScore?: number;
    minDate?: string;
    minScore?: number;
    page?: number;
    size?: number;
    sortBy?: string;
    status?: string;
}

export interface FindingsFindFindingsFromATargetRequest {
    targetId: string;
    teamId: string;
    atDate?: string;
    identifiers?: string;
    labels?: string;
    maxDate?: string;
    maxScore?: number;
    minDate?: string;
    minScore?: number;
    page?: number;
    size?: number;
    sortBy?: string;
    status?: string;
}

export interface FindingsListFindingOverwritesRequest {
    findingId: string;
    teamId: string;
}

export interface FindingsListFindingsRequest {
    teamId: string;
    atDate?: string;
    identifier?: string;
    identifiers?: string;
    issueID?: string;
    labels?: string;
    maxDate?: string;
    maxScore?: number;
    minDate?: string;
    minScore?: number;
    page?: number;
    size?: number;
    sortBy?: string;
    status?: string;
    targetID?: string;
}

export interface FindingsListFindingsIssuesRequest {
    teamId: string;
    atDate?: string;
    identifiers?: string;
    labels?: string;
    maxDate?: string;
    minDate?: string;
    page?: number;
    size?: number;
    sortBy?: string;
    status?: string;
    targetID?: string;
}

export interface FindingsListFindingsLabelsRequest {
    teamId: string;
    atDate?: string;
    identifiers?: string;
    maxDate?: string;
    minDate?: string;
    status?: string;
}

export interface FindingsListFindingsTargetsRequest {
    teamId: string;
    atDate?: string;
    identifiers?: string;
    issueID?: string;
    labels?: string;
    maxDate?: string;
    minDate?: string;
    page?: number;
    size?: number;
    sortBy?: string;
    status?: string;
}

export interface FindingsSubmitAFindingOverwriteRequest {
    findingId: string;
    teamId: string;
    payload: FindingOverwritePayload;
}

export interface FindingsSubmitAFindingTicketCreationRequest {
    findingId: string;
    teamId: string;
    payload: FindingTicketCreationPayload;
}

/**
 * 
 */
export class FindingsApi extends runtime.BaseAPI {

    /**
     * Find a finding.
     * Find finding findings
     */
    async findingsFindFindingRaw(requestParameters: FindingsFindFindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Finding>> {
        if (requestParameters.findingId === null || requestParameters.findingId === undefined) {
            throw new runtime.RequiredError('findingId','Required parameter requestParameters.findingId was null or undefined when calling findingsFindFinding.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsFindFinding.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/{finding_id}`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters.findingId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingFromJSON(jsonValue));
    }

    /**
     * Find a finding.
     * Find finding findings
     */
    async findingsFindFinding(requestParameters: FindingsFindFindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Finding> {
        const response = await this.findingsFindFindingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find all findings from a team and issue.
     * Find findings from a Issue findings
     */
    async findingsFindFindingsFromAIssueRaw(requestParameters: FindingsFindFindingsFromAIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsList>> {
        if (requestParameters.issueId === null || requestParameters.issueId === undefined) {
            throw new runtime.RequiredError('issueId','Required parameter requestParameters.issueId was null or undefined when calling findingsFindFindingsFromAIssue.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsFindFindingsFromAIssue.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.labels !== undefined) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.maxScore !== undefined) {
            queryParameters['maxScore'] = requestParameters.maxScore;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.minScore !== undefined) {
            queryParameters['minScore'] = requestParameters.minScore;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/issues/{issue_id}`.replace(`{${"issue_id"}}`, encodeURIComponent(String(requestParameters.issueId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsListFromJSON(jsonValue));
    }

    /**
     * Find all findings from a team and issue.
     * Find findings from a Issue findings
     */
    async findingsFindFindingsFromAIssue(requestParameters: FindingsFindFindingsFromAIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsList> {
        const response = await this.findingsFindFindingsFromAIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find all findings from a team and target.
     * Find findings from a Target findings
     */
    async findingsFindFindingsFromATargetRaw(requestParameters: FindingsFindFindingsFromATargetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsList>> {
        if (requestParameters.targetId === null || requestParameters.targetId === undefined) {
            throw new runtime.RequiredError('targetId','Required parameter requestParameters.targetId was null or undefined when calling findingsFindFindingsFromATarget.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsFindFindingsFromATarget.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.labels !== undefined) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.maxScore !== undefined) {
            queryParameters['maxScore'] = requestParameters.maxScore;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.minScore !== undefined) {
            queryParameters['minScore'] = requestParameters.minScore;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/targets/{target_id}`.replace(`{${"target_id"}}`, encodeURIComponent(String(requestParameters.targetId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsListFromJSON(jsonValue));
    }

    /**
     * Find all findings from a team and target.
     * Find findings from a Target findings
     */
    async findingsFindFindingsFromATarget(requestParameters: FindingsFindFindingsFromATargetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsList> {
        const response = await this.findingsFindFindingsFromATargetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Finding Overwrites.
     * List Finding Overwrites findings
     */
    async findingsListFindingOverwritesRaw(requestParameters: FindingsListFindingOverwritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FindingOverwrite>>> {
        if (requestParameters.findingId === null || requestParameters.findingId === undefined) {
            throw new runtime.RequiredError('findingId','Required parameter requestParameters.findingId was null or undefined when calling findingsListFindingOverwrites.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsListFindingOverwrites.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/{finding_id}/overwrites`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters.findingId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FindingOverwriteFromJSON));
    }

    /**
     * List Finding Overwrites.
     * List Finding Overwrites findings
     */
    async findingsListFindingOverwrites(requestParameters: FindingsListFindingOverwritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FindingOverwrite>> {
        const response = await this.findingsListFindingOverwritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all findings from a team.
     * list findings findings
     */
    async findingsListFindingsRaw(requestParameters: FindingsListFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsList>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsListFindings.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifier !== undefined) {
            queryParameters['identifier'] = requestParameters.identifier;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.issueID !== undefined) {
            queryParameters['issueID'] = requestParameters.issueID;
        }

        if (requestParameters.labels !== undefined) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.maxScore !== undefined) {
            queryParameters['maxScore'] = requestParameters.maxScore;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.minScore !== undefined) {
            queryParameters['minScore'] = requestParameters.minScore;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.targetID !== undefined) {
            queryParameters['targetID'] = requestParameters.targetID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsListFromJSON(jsonValue));
    }

    /**
     * List all findings from a team.
     * list findings findings
     */
    async findingsListFindings(requestParameters: FindingsListFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsList> {
        const response = await this.findingsListFindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List number of findings and max score per issue.
     * list findings issues findings
     */
    async findingsListFindingsIssuesRaw(requestParameters: FindingsListFindingsIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsIssuesList>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsListFindingsIssues.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.labels !== undefined) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.targetID !== undefined) {
            queryParameters['targetID'] = requestParameters.targetID;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/issues`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsIssuesListFromJSON(jsonValue));
    }

    /**
     * List number of findings and max score per issue.
     * list findings issues findings
     */
    async findingsListFindingsIssues(requestParameters: FindingsListFindingsIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsIssuesList> {
        const response = await this.findingsListFindingsIssuesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all findings labels.
     * List findings labels findings
     */
    async findingsListFindingsLabelsRaw(requestParameters: FindingsListFindingsLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsLabels>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsListFindingsLabels.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/labels`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsLabelsFromJSON(jsonValue));
    }

    /**
     * List all findings labels.
     * List findings labels findings
     */
    async findingsListFindingsLabels(requestParameters: FindingsListFindingsLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsLabels> {
        const response = await this.findingsListFindingsLabelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List number of findings and max score per target.
     * list findings targets findings
     */
    async findingsListFindingsTargetsRaw(requestParameters: FindingsListFindingsTargetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsTargetsList>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsListFindingsTargets.');
        }

        const queryParameters: any = {};

        if (requestParameters.atDate !== undefined) {
            queryParameters['atDate'] = requestParameters.atDate;
        }

        if (requestParameters.identifiers !== undefined) {
            queryParameters['identifiers'] = requestParameters.identifiers;
        }

        if (requestParameters.issueID !== undefined) {
            queryParameters['issueID'] = requestParameters.issueID;
        }

        if (requestParameters.labels !== undefined) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.maxDate !== undefined) {
            queryParameters['maxDate'] = requestParameters.maxDate;
        }

        if (requestParameters.minDate !== undefined) {
            queryParameters['minDate'] = requestParameters.minDate;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['sortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/targets`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsTargetsListFromJSON(jsonValue));
    }

    /**
     * List number of findings and max score per target.
     * list findings targets findings
     */
    async findingsListFindingsTargets(requestParameters: FindingsListFindingsTargetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsTargetsList> {
        const response = await this.findingsListFindingsTargetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Overwrite data for a specific finding.
     * Submit a Finding Overwrite findings
     */
    async findingsSubmitAFindingOverwriteRaw(requestParameters: FindingsSubmitAFindingOverwriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingsList>> {
        if (requestParameters.findingId === null || requestParameters.findingId === undefined) {
            throw new runtime.RequiredError('findingId','Required parameter requestParameters.findingId was null or undefined when calling findingsSubmitAFindingOverwrite.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsSubmitAFindingOverwrite.');
        }

        if (requestParameters.payload === null || requestParameters.payload === undefined) {
            throw new runtime.RequiredError('payload','Required parameter requestParameters.payload was null or undefined when calling findingsSubmitAFindingOverwrite.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/{finding_id}/overwrites`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters.findingId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindingOverwritePayloadToJSON(requestParameters.payload),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingsListFromJSON(jsonValue));
    }

    /**
     * Overwrite data for a specific finding.
     * Submit a Finding Overwrite findings
     */
    async findingsSubmitAFindingOverwrite(requestParameters: FindingsSubmitAFindingOverwriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingsList> {
        const response = await this.findingsSubmitAFindingOverwriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a ticket associated with the finding in a ticket tracker tool.
     * Submit a Finding Ticket Creation findings
     */
    async findingsSubmitAFindingTicketCreationRaw(requestParameters: FindingsSubmitAFindingTicketCreationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindingTicketcreation>> {
        if (requestParameters.findingId === null || requestParameters.findingId === undefined) {
            throw new runtime.RequiredError('findingId','Required parameter requestParameters.findingId was null or undefined when calling findingsSubmitAFindingTicketCreation.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling findingsSubmitAFindingTicketCreation.');
        }

        if (requestParameters.payload === null || requestParameters.payload === undefined) {
            throw new runtime.RequiredError('payload','Required parameter requestParameters.payload was null or undefined when calling findingsSubmitAFindingTicketCreation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/findings/{finding_id}/ticketcreation`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters.findingId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindingTicketCreationPayloadToJSON(requestParameters.payload),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindingTicketcreationFromJSON(jsonValue));
    }

    /**
     * Create a ticket associated with the finding in a ticket tracker tool.
     * Submit a Finding Ticket Creation findings
     */
    async findingsSubmitAFindingTicketCreation(requestParameters: FindingsSubmitAFindingTicketCreationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindingTicketcreation> {
        const response = await this.findingsSubmitAFindingTicketCreationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
