/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Policy,
    PolicyFromJSON,
    PolicyToJSON,
    PolicyPayload,
    PolicyPayloadFromJSON,
    PolicyPayloadToJSON,
    PolicyUpdatePayload,
    PolicyUpdatePayloadFromJSON,
    PolicyUpdatePayloadToJSON,
} from '../models';

export interface PoliciesCreateRequest {
    teamId: string;
    payload: PolicyPayload;
}

export interface PoliciesDeleteRequest {
    policyId: string;
    teamId: string;
}

export interface PoliciesListRequest {
    teamId: string;
}

export interface PoliciesShowRequest {
    policyId: string;
    teamId: string;
}

export interface PoliciesUpdateRequest {
    policyId: string;
    teamId: string;
    payload: PolicyUpdatePayload;
}

/**
 * 
 */
export class PoliciesApi extends runtime.BaseAPI {

    /**
     * Create a new policy.
     * create policies
     */
    async policiesCreateRaw(requestParameters: PoliciesCreateRequest): Promise<runtime.ApiResponse<Policy>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling policiesCreate.');
        }

        if (requestParameters.payload === null || requestParameters.payload === undefined) {
            throw new runtime.RequiredError('payload','Required parameter requestParameters.payload was null or undefined when calling policiesCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/policies`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolicyPayloadToJSON(requestParameters.payload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyFromJSON(jsonValue));
    }

    /**
     * Create a new policy.
     * create policies
     */
    async policiesCreate(requestParameters: PoliciesCreateRequest): Promise<Policy> {
        const response = await this.policiesCreateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete a policy.
     * delete policies
     */
    async policiesDeleteRaw(requestParameters: PoliciesDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.policyId === null || requestParameters.policyId === undefined) {
            throw new runtime.RequiredError('policyId','Required parameter requestParameters.policyId was null or undefined when calling policiesDelete.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling policiesDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/policies/{policy_id}`.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters.policyId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a policy.
     * delete policies
     */
    async policiesDelete(requestParameters: PoliciesDeleteRequest): Promise<void> {
        await this.policiesDeleteRaw(requestParameters);
    }

    /**
     * List all policies from a team.
     * list policies
     */
    async policiesListRaw(requestParameters: PoliciesListRequest): Promise<runtime.ApiResponse<Array<Policy>>> {
        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling policiesList.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/policies`.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PolicyFromJSON));
    }

    /**
     * List all policies from a team.
     * list policies
     */
    async policiesList(requestParameters: PoliciesListRequest): Promise<Array<Policy>> {
        const response = await this.policiesListRaw(requestParameters);
        return await response.value();
    }

    /**
     * Show information about a policy.
     * show policies
     */
    async policiesShowRaw(requestParameters: PoliciesShowRequest): Promise<runtime.ApiResponse<Policy>> {
        if (requestParameters.policyId === null || requestParameters.policyId === undefined) {
            throw new runtime.RequiredError('policyId','Required parameter requestParameters.policyId was null or undefined when calling policiesShow.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling policiesShow.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/policies/{policy_id}`.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters.policyId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyFromJSON(jsonValue));
    }

    /**
     * Show information about a policy.
     * show policies
     */
    async policiesShow(requestParameters: PoliciesShowRequest): Promise<Policy> {
        const response = await this.policiesShowRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update information about a policy.
     * update policies
     */
    async policiesUpdateRaw(requestParameters: PoliciesUpdateRequest): Promise<runtime.ApiResponse<Policy>> {
        if (requestParameters.policyId === null || requestParameters.policyId === undefined) {
            throw new runtime.RequiredError('policyId','Required parameter requestParameters.policyId was null or undefined when calling policiesUpdate.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling policiesUpdate.');
        }

        if (requestParameters.payload === null || requestParameters.payload === undefined) {
            throw new runtime.RequiredError('payload','Required parameter requestParameters.payload was null or undefined when calling policiesUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/policies/{policy_id}`.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters.policyId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PolicyUpdatePayloadToJSON(requestParameters.payload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyFromJSON(jsonValue));
    }

    /**
     * Update information about a policy.
     * update policies
     */
    async policiesUpdate(requestParameters: PoliciesUpdateRequest): Promise<Policy> {
        const response = await this.policiesUpdateRaw(requestParameters);
        return await response.value();
    }

}
