/* tslint:disable */
/* eslint-disable */
/**
 * Vulcan API
 * Public API for Vulcan Vulnerability Scan Engine
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Report,
    ReportFromJSON,
    ReportToJSON,
    Reportemail,
    ReportemailFromJSON,
    ReportemailToJSON,
} from '../models';

export interface ScanReportEmailRequest {
    scanId: string;
    teamId: string;
}

export interface ScanReportGenerateRequest {
    scanId: string;
    teamId: string;
}

export interface ScanReportSendRequest {
    scanId: string;
    teamId: string;
}

export interface ScanReportShowRequest {
    scanId: string;
    teamId: string;
}

/**
 * 
 */
export class ScanReportApi extends runtime.BaseAPI {

    /**
     * Retrieve the report in html format to be sent by email.
     * email scan report
     */
    async scanReportEmailRaw(requestParameters: ScanReportEmailRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Reportemail>> {
        if (requestParameters.scanId === null || requestParameters.scanId === undefined) {
            throw new runtime.RequiredError('scanId','Required parameter requestParameters.scanId was null or undefined when calling scanReportEmail.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling scanReportEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/scans/{scan_id}/report/email`.replace(`{${"scan_id"}}`, encodeURIComponent(String(requestParameters.scanId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportemailFromJSON(jsonValue));
    }

    /**
     * Retrieve the report in html format to be sent by email.
     * email scan report
     */
    async scanReportEmail(requestParameters: ScanReportEmailRequest, initOverrides?: RequestInit): Promise<Reportemail> {
        const response = await this.scanReportEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Triggers report generation. The report will be generated asynchronously on Vulcan Backend.
     * generate scan report
     */
    async scanReportGenerateRaw(requestParameters: ScanReportGenerateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.scanId === null || requestParameters.scanId === undefined) {
            throw new runtime.RequiredError('scanId','Required parameter requestParameters.scanId was null or undefined when calling scanReportGenerate.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling scanReportGenerate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/scans/{scan_id}/report`.replace(`{${"scan_id"}}`, encodeURIComponent(String(requestParameters.scanId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Triggers report generation. The report will be generated asynchronously on Vulcan Backend.
     * generate scan report
     */
    async scanReportGenerate(requestParameters: ScanReportGenerateRequest, initOverrides?: RequestInit): Promise<void> {
        await this.scanReportGenerateRaw(requestParameters, initOverrides);
    }

    /**
     * Send the generated report by email to the team recipients.
     * send scan report
     */
    async scanReportSendRaw(requestParameters: ScanReportSendRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.scanId === null || requestParameters.scanId === undefined) {
            throw new runtime.RequiredError('scanId','Required parameter requestParameters.scanId was null or undefined when calling scanReportSend.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling scanReportSend.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/scans/{scan_id}/report/send`.replace(`{${"scan_id"}}`, encodeURIComponent(String(requestParameters.scanId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send the generated report by email to the team recipients.
     * send scan report
     */
    async scanReportSend(requestParameters: ScanReportSendRequest, initOverrides?: RequestInit): Promise<void> {
        await this.scanReportSendRaw(requestParameters, initOverrides);
    }

    /**
     * Show information about a scan report
     * show scan report
     */
    async scanReportShowRaw(requestParameters: ScanReportShowRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Report>> {
        if (requestParameters.scanId === null || requestParameters.scanId === undefined) {
            throw new runtime.RequiredError('scanId','Required parameter requestParameters.scanId was null or undefined when calling scanReportShow.');
        }

        if (requestParameters.teamId === null || requestParameters.teamId === undefined) {
            throw new runtime.RequiredError('teamId','Required parameter requestParameters.teamId was null or undefined when calling scanReportShow.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/teams/{team_id}/scans/{scan_id}/report`.replace(`{${"scan_id"}}`, encodeURIComponent(String(requestParameters.scanId))).replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters.teamId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportFromJSON(jsonValue));
    }

    /**
     * Show information about a scan report
     * show scan report
     */
    async scanReportShow(requestParameters: ScanReportShowRequest, initOverrides?: RequestInit): Promise<Report> {
        const response = await this.scanReportShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
